name: journey_radar_mobile
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  animations: ^2.0.11
  bloc: ^8.1.4
  collection: ^1.18.0
  curl_logger_dio_interceptor: ^1.0.0
  dio: ^5.8.0+1
  dio_smart_retry: ^6.0.0
  easy_localization: ^3.0.7
  email_validator: ^3.0.0
  equatable: ^2.0.7
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_cache_manager: ^3.4.1
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.4
  flutter_secure_storage: ^9.2.2
  flutter_tts: ^4.2.3
  fluttertoast: ^8.2.10
  get_it: ^8.0.2
  go_router: ^14.6.2
  html_unescape: ^2.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  introduction_screen: ^3.1.16
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.3.0
  logger: ^2.4.0
  lucide_icons_flutter: ^3.0.3
  multi_select_flutter: ^4.1.3
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  platform: ^3.1.6
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  sizer: ^3.0.5
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
